input_graph_name: ecommerce_hetero_graph_with_sf.dgl
aggregate_fn: mean
n_epochs: 10
batch_size: 512
hidden_dim: 128
edge_hidden_dim: 64
output_dim: 64
dropout: 0.5
pred: cos
learning_rate: 0.0001
num_layers: 3
num_workers: 0
number_of_egdes: 5000
train_full: True